source ~/.config/nvim/plug/plugins.vim
source ~/.config/nvim/keys/mappings.vim
source ~/.config/nvim/settings/general.vim
source ~/.config/nvim/config/airline.vim
source ~/.config/nvim/config/signify.vim
source ~/.config/nvim/config/floaterm.vim
source ~/.config/nvim/config/wilder.vim
source ~/.config/nvim/settings/term.vim
lua require('pairs')
lua require('notifyP')
lua require('buff')
