require('plugs.plugins')
require('settings.general')
require('settings.mappings')
require('settings.color')
vim.cmd('source ~/.config/nvim/vim/config/dashboard.vim')
vim.cmd('source ~/.config/nvim/vim/settings/term.vim')
vim.cmd('source ~/.config/nvim/vim/config/signify.vim')
require('config.tree')
require('config.pairs')
require('config.notifyP')
require('config.buff')
require('config.lsp.lspinstaller')
require('config.lsp.cmp')
require('config.lsp.lspkin')
require('config.blank')
require('config.lLine')
require('config.gBlame')
require('config.tele')
require('config.vide')
vim.cmd('source ~/.config/nvim/vim/config/floaterm.vim')
vim.cmd('source ~/.config/nvim/vim/config/nerdtree.vim')
vim.cmd('source ~/.config/nvim/vim/config/wilder.vim')
