vim.cmd('source ~/.config/nvim/plug/plugins.vim')
vim.cmd('source ~/.config/nvim/settings/mappings.vim')
vim.cmd('source ~/.config/nvim/settings/general.vim')
vim.cmd('source ~/.config/nvim/config/dashboard.vim')
vim.cmd('source ~/.config/nvim/settings/term.vim')
vim.cmd('source ~/.config/nvim/config/signify.vim')
vim.cmd('source ~/.config/nvim/config/wilder.vim')
require('tree')
require('pairs')
require('notifyP')
require('buff')
require('lsp.lspinstaller')
require('lsp.cmp')
require('lsp.lspkin')
require('blank')
require('lLine')
require('tele')
require('vide')
vim.cmd('source ~/.config/nvim/config/floaterm.vim')
vim.cmd('source ~/.config/nvim/config/nerdtree.vim')
vim.cmd('source ~/.config/nvim/config/gBlame.vim')
